easy_admin:
    entities:
        - App\Entity\Appointment
        - App\Entity\Attribute
        - App\Entity\AttributeType
        - App\Entity\Location
        - App\Entity\Speaker
        - App\Entity\Talk
