parameters:
    email_sender: '%env(EMAIL_SENDER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $emailSender: '%email_sender%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Action\:
        resource: '../src/Action'
        tags: ['controller.service_arguments']
