name: PHPUnit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install js dependencies
      run: yarn install --no-progress

    - name: Build webpack
      run: yarn encore prod

    - name: Create database
      run: bin/console doctrine:database:create --env test

    - name: Create database schema
      run: bin/console doctrine:schema:create --env test

    - name: Run test suite
      run: bin/phpunit
